local telescope = require "telescope"
telescope.setup {
  defaults = {},
  pickers = {
    find_files = {
      find_command = {
        "rg",
        "--files",
        "--hidden",
        "--no-ignore",
        "--follow",
        "--glob",
        "!.git/*", -- 排除.git目录中的文件
        -- "--glob",
        -- "*.cpp",
        -- "--glob",
        -- "*.c",
        -- "--glob",
        -- "*.py",
        -- "--glob",
        -- "*.h",
        -- "--glob",
        -- "*.hpp",
        -- "--glob",
        -- "*ake*ile", -- 匹配所有包含 'ake' 并以 'ile' 结尾的文件，如 Makefile, CMakeLists.txt
        -- "--glob",
        -- "CMakeLists.txt",
        -- "--glob",
        -- "*.rs",
        -- "--glob",
        -- "*.java",
        -- "--glob",
        -- "*.go",
        -- "--glob",
        -- "*.md",
        -- "--glob",
        -- "*.txt",
        -- "--glob",
        -- "*.tex",
        -- "--glob",
        -- "*.lua",
        -- "--glob",
        -- "*.sh",
        -- "--glob",
        -- "*.bash",
        -- "--glob",
        -- "*.m",
        -- "--glob",
        -- "*.xml",
        -- "--glob",
        -- "*.json",
        -- "--glob",
        -- "*.yaml",
        -- "--glob",
        -- "*.yml",
        -- "--glob",
        -- "*.toml",
        -- "--glob",
        -- "*.html",
        -- "--glob",
        -- "*.css",
        -- "--glob",
        -- "*.js",
        -- "--glob",
        -- "*rc", -- 匹配所有以 'rc' 结尾的文件，如 .vimrc, .bashrc
        -- "--glob",
        -- ".dockerignore",
        -- "--glob",
        -- ".gitignore",
        -- "--glob",
        -- "Dockerfile",
        -- "--glob",
        -- "docker-compose*",
      },
    },
  },
}
